apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{int .Values.replicas }}
  revisionHistoryLimit: 3
  minReadySeconds: 5
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      annotations:
        # This is to make harness forcefully deploy a new verion everytime I run the pipleline even if there are no changes.
        # With out this when there are no changes, there is no green pod and half of the requests are failing
        harness.io/deployTimestamp: {{ .Values.deployTimestamp }}
      name: "{{ .Values.name }}-{{ .Values.version }}"
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.version }}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: "{{ .Values.service.targetPort }}"
              protocol: {{ .Values.service.protocol }}