apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: sample-istio-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway  # The selector should match the Istio ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"  # Accept requests for any host
