apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - sample-istio-gateway  # The gateway that this VirtualService uses
  http:
    - match:
        - uri:
            prefix: /harness  # Route traffic only for '/path'
      delegate:
        name: {{ .Values.name }}-virtual-service
        namespace: {{ .Values.namespace }}
