apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sample-virtualservice
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - sample-istio-gateway  # The gateway that this VirtualService uses
  http:
    - match:
        - uri:
            prefix: /harness  # Route traffic only for '/path'
      route:
        - destination:
            host: {{.Values.name}}-service  # The service to route traffic to
            port:
              number: {{ .Values.service.port }}  # The port on which the service is running
