name: <+service.name>
namespace: <+service.name>
version: <+pipeline.variables.artifactVersion>
#tag: <+artifacts.primary.tag>
#repository: <+serviceVariables.repo>

#image: <+serviceVariables.repo>/<+service.name>:<+artifacts.primary.tag>
image: <+service.name>

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  protocol: TCP
#  nodePort: 30007

extAuthProvider: sample-ext-authz-http

deployTimestamp: <+pipeline.variables.deployTimestamp>